<div class="hot-all-categories">
    <h3><?=__('Our Categories');?></h3>
    <div class="category-list">
        <span class="category-title"><a href=""><?=__('Tartan Fabric, Plaid Materials')?></a></span>
        <span class="category-title"><a href=""><?=__('Ribbon in ANY Tartan')?></a></span>
        <span class="category-title"><a href=""><?=__('Custom-Made in ANY Tartan')?></a></span>
        <span class="category-title"><a href=""><?=__('Menswear & Accessories')?></a></span>
        <span class="category-title"><a href=""><?=__('Ladieswear & Accessories')?></a></span>
        <span class="category-title"><a href=""><?=__('Childrenswear & Accessories')?></a></span>
        <span class="category-title"><a href=""><?=__('Scottish & Celtic Weddings, Hire Tartan')?></a></span>
        <span class="category-title"><a href=""><?=__('Burns Night & Ceilidhs')?></a></span>
        <span class="category-title"><a href=""><?=__('Clan Shops, Affiliates & Partner Tartans')?></a></span>
        <span class="category-title"><a href=""><?=__('Clan Crested Products & Badges')?></a></span>
        <span class="category-title"><a href=""><?=__('Clan Sportswear & Highland Games Gear')?></a></span>
        <span class="category-title"><a href=""><?=__('Scottish, Celtic Jewellery, Tartan Gifts')?></a></span>
        <span class="category-title"><a href=""><?=__('Home  & Tartan Furnishings')?></a></span>
        <span class="category-title"><a href=""><?=__('Tartan Upholstery, Cars')?></a></span>
        <span class="category-title"><a href=""><?=__('Design & Weave your own Tartan')?></a></span>
        <span class="category-title"><a href=""><?=__('Irish Tartans & Accessories')?></a></span>
        <span class="category-title"><a href=""><?=__('Welsh Tartans & Accessories')?></a></span>
        <span class="category-title"><a href=""><?=__('Pipers & Highland Dancers')?></a></span>
        <span class="category-title"><a href=""><?=__('Books, Memorabilia.')?></a></span>
        <span class="category-title"><a href=""><?=__('Tartan for Pets,  Beasties')?></a></span>
        <span class="category-title"><a href=""><?=__('Corporate Tartans, Products')?></a></span>
        <span class="category-title"><a href=""><?=__('World & District Tartans')?></a></span>
        <span class="category-title"><a href=""><?=__('Crieff & Comrie Merchandise')?></a></span>
    </div>
</div>