<div id="category-list">
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_1.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_2.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_3.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_4.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_5.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_6.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_7.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_8.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_9.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_10.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_11.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_12.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_13.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_14.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_15.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
	<div class="category">
		<img src="<?=$this->getViewFileUrl('images/category/cat_16.png'); ?>" alt="house of tartan" />
		<span class="category_name">Tartan Fabric, Plaid Materials</span>
	</div>
</div>