<!-- Admin Managible Footer-->
<?php /*$this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('house_of_tartan_footer')->toHtml(); */?>

<div class="main-container display-desktop">
	<div class="container">
		<div class="bottom-footer">
			<div class="inner-container">
				<img src="<?=$this->getViewFileUrl('images/logo.svg'); ?>" alt="house of tartan" />
				<div class="social-Listing">
					<ul>
						<li><a href=""><i class="fab fa-facebook-f"></i></a></li>
						<li><a href=""><i class="fab fa-twitter"></i></a></li>
						<li><a href=""><i class="fab fa-linkedin-in"></i></a></li>
						<li><a href=""><i class="fab fa-instagram"></i></a></li>
					</ul>
				</div>
			</div>
			<div class="inner-container">
				<div class="footer-Listing">
					<ul>
						<li><a href="">Tartan Finder</a></li>
						<li><a href="">Clan Finder</a></li>
						<li><a href="">Design Your Own Tartan</a></li>
						<li><a href="">Clan Shops & Affiliates</a></li>
						<li><a href="">How To Measure</a></li>
						<li><a href="">Gift Vouchers</a></li>
					</ul>
				</div>
			</div>
			<div class="inner-container">
				<div class="footer-Listing">
					<ul>
						<li><a href="">Tartan Design & Registration Service</a></li>
						<li><a href="">Delivery & Shipping Info</a></li>
						<li><a href="">Gallery & Testimonials</a></li>
						<li><a href="">About Us</a></li>
						<li><a href="">Tartan Events</a></li>
						<li><a href="">Our Blog</a></li>
					</ul>
				</div>
			</div>
			<div class="inner-container">
				<div class="footer-Listing">
					<ul>
						<li><a href="">Contact Us</a></li>
						<li><a href="">Customer Service</a></li>
						<li><a href="">Privacy Policy</a></li>
						<li><a href="">Terms & Conditions</a></li>
					</ul>
				</div>
			</div>

			<div class="inner-container">
				<div class="footer-Listing">
					<p class="address-footer">House of Tartan Ltd<br>
						9 - 11 East High Street<br>
						CRIEFF, Perthshire,<br>
					Scotland, PH7 3AF</p>

					<p class="phone-number">Tel +44 1764 656671</p>
				</div>
			</div>

			<div class="inner-container">
				<div class="footer-Listing">
					<ul class="logo-section">
						<li>
							<img src="<?=$this->getViewFileUrl('images/Image_1.png'); ?>" alt="house of tartan" />
							</li>
						<li>
							<img src="<?=$this->getViewFileUrl('images/Image_2.png'); ?>" alt="house of tartan" />
							</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="payment-option">
		Supported Payment Methods 
		<img src="<?=$this->getViewFileUrl('images/Visa.png'); ?>" alt="visa" />
		<img src="<?=$this->getViewFileUrl('images/american_express.jpg'); ?>" alt="american express" />
		<img src="<?=$this->getViewFileUrl('images/master_card.png'); ?>" alt="master card" />
		<img src="<?=$this->getViewFileUrl('images/paypal.png'); ?>" alt="paypal" />
	</div>
	<div class="copyright-section">
		<div class="copyright-year">
			© 2020 House of Tartan, Crieff
		</div>
		<div class="copyright-text">
			HOUSE OF TARTAN®, MacBeanie®, and the HoT PIPERMARK® are registered trademarks of House of Tartan Ltd, Scotland
			website by mtc.
		</div>
	</div>
</div>