<div class="homepage-header-section">
	<div class="homepage-content-title">This is the <span id="title">HOUSE of TARTAN®</span>, the <span id="original">ORIGINAL</span> Tartan Website.</div> 
	<div class="container-main-para">
		<div class="main-content-para"><span id="years">For 25 years a World Leader&nbsp;</span>. Speak to the definitive Tartan Industry experts and Get Help Fast. If you can’t find what you want, please phone <a href="tel: +44 1764 656671">+44 1764 656671</a> or <a href="mailto:abc@testmail.com" >email us</a>.<span id="end">We make Tartan Easy.</span>
		</div>
	</div>
</div>