<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */



 

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<nav class="navigation hot" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php /* @noEscape */ /*$_menuHtml */?>
        <?php /* $block->getChildHtml() */?>
        <li class="level0 nav-6 category-item last level-top ui-menu-item">
            <a href="#" class="level-top ui-menu-item-wrapper">
                <span><?=__("Tartan Finder")?></span>
            </a>
        </li>
        <li class="level0 nav-6 category-item last level-top ui-menu-item">
            <a href="#" class="level-top ui-menu-item-wrapper">
                <span><?=__("Surname/Clan Finder")?></span>
            </a>
        </li>
        <li class="level0 nav-6 category-item last level-top ui-menu-item">
            <a href="#" class="level-top ui-menu-item-wrapper">
                <span><?=__("Design Your Own")?></span>
            </a>
        </li>
        <li class="level0 nav-6 category-item last level-top ui-menu-item">
            <a href="#" class="level-top ui-menu-item-wrapper">
                <span><?=__("Clan Shops & Affilliates")?></span>
            </a>
        </li>
        
    </ul>
</nav>
